### ISSUE TITLE
Migrate local modules to nf-core/modules

### ISSUE THREAD

**Issue by apeltzer** [nf-core/smrnaseq#368]
### Description of feature

Wherever possible (e.g. BLAT), this should be performed. Prime candidates for this are:

* BLAT
* edgeR
* mirDeep2
* mirtop
* mirtrace
* seqcluster
* bowtie1/bowtie2 modules (~5 of them)
 

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/smrnaseq/issues/395
- [ ] https://github.com/nf-core/smrnaseq/issues/402
- [ ] https://github.com/nf-core/smrnaseq/issues/410
- [ ] https://github.com/nf-core/smrnaseq/issues/403
- [ ] https://github.com/nf-core/smrnaseq/issues/417
- [ ] https://github.com/nf-core/smrnaseq/issues/413
- [ ] https://github.com/nf-core/smrnaseq/issues/416
- [ ] https://github.com/nf-core/smrnaseq/issues/422
- [ ] https://github.com/nf-core/smrnaseq/issues/431
- [ ] https://github.com/nf-core/smrnaseq/issues/433
- [ ] https://github.com/nf-core/smrnaseq/issues/434
- [ ] https://github.com/nf-core/smrnaseq/issues/436
- [ ] https://github.com/nf-core/smrnaseq/issues/437
- [ ] https://github.com/nf-core/smrnaseq/issues/443
```

**Comment by apeltzer** [comment]
I will check this one if we really want to overinvest on this ticket here - I think the progress is already great 👍🏻
