### ISSUE TITLE
Test profile not working

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/smrnaseq#371]
I recently tried running the test profile using docker and singularity and they both fail for different reasons:
Singularity command:
nextflow run ../../main.nf -profile test,singularity --outdir results
nextflow log: [singularity.log](https://github.com/user-attachments/files/16613900/singularity.log)

Docker command:
nextflow run ../../main.nf -profile test,docker --outdir results -resume

nextflow log: [docker.log](https://github.com/user-attachments/files/16613899/docker.log)

Run details:
Branch: dev, commit: 374ec02e9f8767a0b2a02180b74724f40be43f03

More info:
Test profile seems to be working in master.

Related issues:
https://github.com/nf-core/smrnaseq/issues/367

FYI @apeltzer @atrigila @grst 
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/smrnaseq/issues/373
- [x] FIx test profile not working with singularity
- [ ] https://github.com/nf-core/smrnaseq/issues/375
```

**Comment by nschcolnicov** [comment]
For the first docker command, the issue seems to be related to having the params protocol set to "Custom" while the MIRTRACE_RUN process expects "custom"

**Comment by nschcolnicov** [comment]
Seems that the original singularity issue was related with running the command in gitpod, if I run this command on a different environment, I get this issue:
```ERROR ~ Error executing process > 'NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP (Clone9_N2)'

Caused by:
  Process `NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP (Clone9_N2)` terminated with an error exit status (255)

Command executed:

  [ ! -f  Clone9_N2.fastq.gz ] && ln -sf C9-N2-R1_S8_L001_R1_001.fastq.gz Clone9_N2.fastq.gz
  
  fastp \
      --in1 Clone9_N2.fastq.gz \
      --out1  Clone9_N2.fastp.fastq.gz \
      --thread 2 \
      --json Clone9_N2.fastp.json \
      --html Clone9_N2.fastp.html \
      --adapter_fasta known_adapters.fa \
       \
      -l 17 --max_len1 100 --adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA \
      2> >(tee Clone9_N2.fastp.log >&2)
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_SMRNASEQ:FASTQ_FASTQC_UMITOOLS_FASTP:FASTP":
      fastp: $(fastp --version 2>&1 | sed -e "s/fastp //g")
  END_VERSIONS

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: While bind mounting '/scratch/nextflow/work/schcolni/82/125ce346804217781ff2d6cd5841aa:/scratch/nextflow/work/schcolni/82/125ce346804217781ff2d6cd5841aa': destination is already in the mount point list
  ERROR: sequence and quality have different length:
  @M07660:69:000000000-KDJ4R:1:1114:2947:1908HEGAFAFF1G
  @M076ACTCTTAGCGGTGGATCACTCGGCTCGTGC
  +
  BBBBBBBBBBFFGGGGGGGGGGHHHHHGGGGGGGHG
  ERROR: sequence and quality have different length

Work dir:
  /scratch/nextflow/work/schcolni/82/125ce346804217781ff2d6cd5841aa

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
ERROR ~ Pipeline failed. Please refer to troubleshooting docs: https://nf-co.re/docs/usage/troubleshooting

 -- Check '.nextflow.log' file for details```

**Comment by nschcolnicov** [comment]
The run with singularity seems to be working now, probably the issue was with the running environment:


![Image](https://github.com/user-attachments/assets/12c5d63d-3407-4654-a005-cf7abea368c9)
