### ISSUE TITLE
Review pipeline release checklist

### ISSUE THREAD

**Issue by atrigila** [nf-core/smrnaseq#460]
Review pipeline release checklist and identify if any point should be addressed separately:

## Do: nf-core principles

- [x] Does the pipeline meet the general [nf-core guidelines](/docs/guidelines/pipelines/overview)?

## Do: Local code and modules

- [x] Do local scripts in `bin/` have author and license embedded?
  - [x] Local script licenses if written for the pipeline should not GPL, but ideally MIT (matching with pipeline code, upon which is assumed if not otherwise specified)
- [x] Do all local modules have docker/singularity/conda declarations?
  - [x] Are they ideally in bioconda/biocontainers
- [x] Do all local modules conda/container tool declarations have versions? (and _not_ `latest`, `dev` etc.)
- [x] Do all local modules report versions (if applicable)?
  - [x] Simple modules with e.g. single `grep` operations not necessary
  - [x] It would be good to add with more complex operations such as `awk`
- [x] Should any local modules be in nf-core/modules?

## Do: Documentation

- [x] Documentation is only on the nf-core website (not pointed to other non-nf-core standard places, e.g. not read the docs )
- [x] Is documentation sufficiently described (`usage.md`, `output.md`, `nextflow_schema.json`)?
  - [x] nextflow_schema.json: check if types are correct and that `default` and `enum` are used where applicable
- [x] Are there any typos in the documentation (`usage.md`, `output.md`, `nextflow_schema.json`)
- [x] Is CHANGELOG sufficiently filled in?
  - [x] Check version system is three-point SemVer e.g. 2.1.0
  - [x] Has the date been updated?
- [x] Check citation formatting consistency in `CIATIONS.md`
- [x] Check that all tools are cited
- [x] Check that (all) pipeline author(s) listed themselves in the manifest and other contributors are added in the README

## Do: Code

- [x] Check no overly non-template components (no read the docs, entirely custom logo etc.)
- [x] Check for general code readability
- [x] Check for possible code bugs
- [x] Check for consistency in parameters
  - [x] i.e. `snake_case`
  - [x] All boolean parameters evaluate to `false` (e.g. bad: `params.run_step = true{:groovy}`, good: `params.skip_step = false{:groovy}` )
- [x] Check manifest includes DOI (if present) etc.

## Before you release

1. [x] Check the pipeline follows [nf-core guidelines](/docs/guidelines/pipelines/overview).
2. [x] All continuous-integration tests on the `dev` branch should be passing
   - [x] Check the output of `nf-core lint` for warnings and address all that you can
   - [x] Update any software dependencies that are out of date.
         The linting will warn about available updates via automated API calls to (bio-)conda
3. [x] Check that there are no outstanding issues that need to be addressed, especially bug reports.
4. [x] Finalize the description of the pipeline in the GitHub repository and ensure that you remove any "under development" labels in the description. This wording will be used when a new pipeline gets announced on Twitter.
5. [x] If there is a [release milestone](https://help.github.com/en/github/managing-your-work-on-github/about-milestones), have a look and see if all issues are closed, or can be resolved
   - [x] It's fine to decide that some things should be postponed until the next release - just move them on to the next milestone

**Comment by atrigila** [comment]
@apeltzer the only two missing points from this are :
- Update the version/date of the changelog -> after bump version
- Add license/author to local scripts -> we were unsure who authored those and which license would apply

CC @nschcolnicov

**Comment by apeltzer** [comment]
I can check the scripts - most of them are from @lpantano I believe, not sure which licenses apply.

**Comment by lpantano** [comment]
we can add MIT license for the scripts if they are mine. The mirtop collapse it is mine, the edgeR is a mixed of authors, @ewels created first according to the history of the file in GitHub.

**Comment by apeltzer** [comment]
Sounds great 👍

**Comment by apeltzer** [comment]
#465 is the Pr for the licences - pinged everyone I found in the git history to be 100% compliant ;-)
#466 is the bump-pr, so we can release - also stated 7th of October for personal reasons :-P
